// Initial manually added and detailed products (IDs 1-6)
const initialProducts = [
    {
        id: 1,
        name: "RTX 4080 Graphics Card",
        price: 999.99,
        category: "PC Components",
        image: "images/placeholder-gpu.jpg",
        description: "The latest generation GPU for high-performance 4K gaming and creation. Features 16GB VRAM and DLSS 3.",
        link: "product-detail.html?id=1"
    },
    {
        id: 2,
        name: "32-inch 4K Monitor",
        price: 450.00,
        category: "Displays",
        image: "images/placeholder-monitor.jpg",
        description: "Fast 144Hz refresh rate and vibrant color accuracy. Perfect for professional and gaming use.",
        link: "product-detail.html?id=2"
    },
    {
        id: 3,
        name: "Wireless ANC Headphones",
        price: 179.50,
        category: "Audio",
        image: "images/placeholder-headphones.jpg", 
        description: "Premium sound quality with industry-leading Active Noise Cancellation for deep focus.",
        link: "product-detail.html?id=3"
    },
    {
        id: 4,
        name: "Ergonomic Mechanical Keyboard",
        price: 129.00,
        category: "Peripherals",
        image: "images/placeholder-keyboard.jpg", 
        description: "Tactile switches, customizable RGB backlighting, and a wrist rest for comfort.",
        link: "product-detail.html?id=4"
    },
    // Your new products:
    {
        id: 5,
        name: "Portable Bluetooth Speaker",
        price: 64.99,
        category: "Audio",
        image: "images/placeholder-speaker.jpg",
        description: "Compact speaker with deep bass and 12-hour battery life, water-resistant and rugged.",
        link: "product-detail.html?id=5"
    },
    {
        id: 6,
        name: "Smart Fitness Watch",
        price: 119.00,
        category: "Wearables",
        image: "images/placeholder-watch.jpg",
        description: "Track your health, sleep, and activities with notifications and GPS.",
        link: "product-detail.html?id=6"
    }
];

// --- AUTO-GENERATION FOR MOCK DATA ---
const autoGeneratedCount = 50;
const categories = ["Gadgets", "Accessories", "Cables", "Power", "Storage", "Misc"];
let currentId = 7; // Start IDs after the manual products

for (let i = 0; i < autoGeneratedCount; i++) {
    const category = categories[i % categories.length]; // Cycles through categories
    const randomPrice = (Math.random() * 200 + 10).toFixed(2); // Price between $10 and $210
    
    initialProducts.push({
        id: currentId,
        name: `Generic Item ${currentId} - ${category}`,
        price: parseFloat(randomPrice),
        category: category,
        // You can use a single placeholder image for all generic items
        image: "images/placeholder-generic.jpg", 
        description: `This is a generic placeholder item, great for testing layouts and filtering, belonging to the ${category} category.`,
        link: `product-detail.html?id=${currentId}`
    });
    currentId++;
}

// Export the final combined list (7 manual + 50 generated = 56 total)
const products = initialProducts;